--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AID-LEARNING/libRabbitMQ
build-by-default: true
branches:
  - master
  - pm5
projects:
  libRabbitMQ:
    model: virion
    type: library
    libs:
      - src: SOF3/await-generator/await-generator
        version: ^3.6.1
...
